name: gulf_sky_technician
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  go_router: ^7.0.0
  intl: 0.17.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  google_fonts: ^4.0.4
  dio: ^5.1.1
  shared_preferences: ^2.1.0
  get_it: ^7.4.1
  flutter_native_splash: ^2.2.19
  font_awesome_flutter: ^10.4.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.1
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^14.0.0+1
  firebase_messaging: ^14.5.0
  firebase_core: ^2.11.0
  flutter_launcher_icons: ^0.13.1
  dropdown_search: ^5.0.6
  banner_listtile: ^2.3.0
  image_picker: ^0.8.7+5
  convex_bottom_bar: ^3.2.0
  cool_alert: ^2.0.1
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"